---
features:
  all:
    ###### basic features ######
    - engine_version
    - app_version
    - av_sig_version
    - av_product_states_id
    - is_av_product_states_id_53447
    - av_products_installed
    - country_id
    - city_id
    - geo_name_id
    - locale_english_name_id
    - os_build_lab
    - rtp_state_bitfield
    - ie_ver_id
    - smart_screen
    - is_smart_screen_exists_not_set
    - is_smart_screen_require_admin
    - wdft_is_gamer
    - wdft_region_id
    ###### census features ######
    - census_oem_name_id
    - census_oem_model_id
    - census_os_version
    - census_os_build_number
    - census_os_architecture
    - census_os_branch
    - census_os_edition
    - census_os_install_type_name
    - census_os_ui_locale_id
    - census_os_wu_auto_update_options_name
    - census_genuine_state_name
    - census_activation_channel
    - census_processor_model_id
    - census_system_volume_total_capacity
    - census_primary_disk_total_capacity
    - census_primary_drive_c_ratio
    - census_none_primary_drive_mb
    - census_internal_primary_diagonal_display_size_in_inches
    - census_internal_primary_display_resolution_horizontal
    - census_aspect_ratio
    - census_monitor_dots_per_inch
    - census_display_mega_pixels
    - census_firmware_manufacturer_id
    - census_firmware_version_id
    ###### combination features ######
    - count_versions_engine_app
    - count_versions_engine_os
    - count_versions_os_install_type_2
    - count_versions_os_install_type_4
    - count_versions_os_install_type_6
    - count_versions_av_product_states_1
    - count_versions_av_product_states_2
    - count_versions_av_product_states_4
    - count_versions_av_product_states_6
    - count_versions_av_products_installed_2
    - count_versions_av_products_installed_4
    - count_versions_av_products_installed_6
    - count_versions_smart_screen_2
    - count_versions_smart_screen_4
    - count_versions_smart_screen_6
    - count_region_av_product_states
    - count_region_av_products_installed
    - count_region_smart_screen
    - count_region_os_install_type_name
    - count_country_av_product_states
    - count_country_av_products_installed
    - count_country_smart_screen
    - count_country_os_install_type_name
    - count_av_product_states_av_products_installed
    - count_av_product_states_smart_screen
    - count_av_product_states_os_install_type
    - count_av_products_installed_smart_screen
    - count_av_products_installed_os_install_type
    - count_smart_screen_os_install_type
    - div_system_volume_total_capacity_processor_core_count
    - mul_primary_disk_total_capacity_processor_core_count
    - mul_total_physical_ram_processor_core_count
    - mul_display_size_inches_processor_core_count
    - div_system_volume_total_capacity_total_physical_ram
    - div_primary_disk_total_capacity_total_physical_ram
    - div_display_size_inches_total_physical_ram
    - div_display_resolution_vertical_total_physical_ram
    - version_aggs_2
    - version_aggs_3
    - version_aggs_6
    - lda_engine_ver_smart_screen_3
    - lda_app_ver_smart_screen_3
    - lda_av_sig_ver_smart_screen_3
    - lda_av_product_states_smart_screen_3
    - lda_country_smart_screen_3
    - lda_city_smart_screen_3
    - lda_geo_name_smart_screen_3
    - lda_oem_model_smart_screen_3
    - lda_processor_model_smart_screen_3
    - lda_firmware_ver_smart_screen_3
  count_encode:
    - engine_version
    - app_version
    - av_sig_version
    - organization_id
    - geo_name_id
    - locale_english_name_id
    - os_build_lab
    - ie_ver_id
    - census_oem_name_id
    - census_os_version
    - census_os_build_number
    - census_os_branch
    - census_os_install_type_name
    - census_processor_model_id
    - census_firmware_manufacturer_id
    - census_firmware_version_id
  category_encode:
    - av_product_states_id
    - rtp_state_bitfield
    - smart_screen
    - census_power_platform_role_name
    - census_os_architecture
    - census_os_edition
    - census_os_ui_locale_id
    - census_os_wu_auto_update_options_name
    - census_genuine_state_name
    - census_activation_channel
  rank_encode:
    - av_products_installed
  target_encode:
    - country_id
    - city_id
    - wdft_region_id
    - census_oem_model_id

model:
  name: lightgbm
  model_params:
    boosting_type: dart
    objective: binary
    scale_pos_weight: 1.0
    learning_rate: 0.05
    num_leaves: 512
    max_depth: -1
    min_data_in_leaf: 100
    feature_fraction: 0.65
    bagging_fraction: 0.8
    bagging_freq: 1
    min_child_weight: 10.0
    min_split_gain: 0
    cat_l2: 15.0
    cat_smooth: 30.0
    lambda_l1: 1.5
    lambda_l2: 2.0
    drop_rate: 0.25
    max_drop: 100
    skip_drop: 0.5
    monotone_constraints: null
    random_state: 2025
    verbosity: -1
  train_params:
    num_boost_round: 3000
    verbose_eval: 100
    categorical_feature: auto

cv_strategy:
  method: StratifiedKFold
  n_splits: 5
  seed: 1

dataset:
  input_directory: 'data/input/'
  output_directory: 'data/output/'
  files:
    train: train.pkl
    target: target.pkl
    test: test.pkl
    sample_submit: sample_submission.csv

target: HasDetections

