---
features:
  all:
    ###### basic features ######
    - engine_version
    - app_version
    - av_sig_version
    - av_product_states_id
    - is_av_product_states_id_53447
    - av_products_installed
    # - av_products_enabled
    - country_id
    - city_id
    - organization_id
    - geo_name_id
    - locale_english_name_id
    # - os_suite
    - os_build_lab
    - os_build_lab_split_0
    - os_build_lab_split_1
    # - sku_edition
    - rtp_state_bitfield
    # - is_protected
    # - s_mode
    - ie_ver_id
    - smart_screen
    - is_smart_screen_exists_not_set
    - is_smart_screen_require_admin
    # - is_smart_screen_off
    # - is_smart_screen_on
    # - is_smart_screen_warn
    # - is_smart_screen_block
    # - is_smart_screen_prompt
    # - is_smart_screen_no_exist
    - wdft_is_gamer
    - wdft_region_id
    ###### census features ######
    - census_mdc2_form_factor
    - census_chassis_type_name
    # - census_power_platform_role_name
    - census_oem_name_id
    - census_oem_model_id
    - census_os_version
    - census_os_build_number
    - census_os_build_revision
    - census_os_architecture
    - census_os_branch
    - census_os_edition
    # - census_os_sku_name
    - census_os_install_type_name
    # - census_os_install_language_id
    - census_os_ui_locale_id
    - census_os_wu_auto_update_options_name
    - census_genuine_state_name
    - census_activation_channel
    # - census_processor_core_count
    # - census_processor_manufacturer_id
    - census_processor_model_id
    - census_total_physical_ram
    # - census_primary_disk_type_name
    - census_system_volume_total_capacity
    - census_primary_disk_total_capacity
    - census_primary_drive_c_ratio
    - census_none_primary_drive_mb
    - census_internal_primary_diagonal_display_size_in_inches
    - census_internal_primary_display_resolution_horizontal
    # - census_internal_primary_display_resolution_vertical
    - census_aspect_ratio
    - census_monitor_dots_per_inch
    - census_display_mega_pixels
    - census_firmware_manufacturer_id
    - census_firmware_version_id
    # - census_is_secure_boot_enabled
    # - census_is_touch_enabled
    # - census_is_always_on_always_connected_capable
    ###### timedelta features ######
    # - date
    # - day
    # - hour
    # - minute
    # - hour_minute
    # - day_of_week
    # - os_build_release_year_month
    # - os_version_not_updated_weeks_4
    ###### combination features ######
    - count_versions_engine_av_sig
    - count_versions_engine_app
    - count_versions_engine_os
    - count_versions_av_sig_app
    - count_versions_av_sig_os
    - count_versions_app_os
    - count_versions_os_install_type_1
    - count_versions_os_install_type_2
    - count_versions_os_install_type_3
    - count_versions_os_install_type_4
    - count_versions_os_install_type_5
    - count_versions_os_install_type_6
    - count_versions_av_product_states_1
    - count_versions_av_product_states_2
    - count_versions_av_product_states_3
    - count_versions_av_product_states_4
    - count_versions_av_product_states_5
    - count_versions_av_product_states_6
    - count_versions_av_products_installed_1
    - count_versions_av_products_installed_2
    - count_versions_av_products_installed_3
    - count_versions_av_products_installed_4
    - count_versions_av_products_installed_5
    - count_versions_av_products_installed_6
    - count_versions_smart_screen_1
    - count_versions_smart_screen_2
    - count_versions_smart_screen_3
    - count_versions_smart_screen_4
    - count_versions_smart_screen_5
    - count_versions_smart_screen_6
    # - count_week_av_product_states
    # - count_week_av_products_installed
    # - count_week_smart_screen
    # - count_week_os_install_type_name
    - count_region_av_product_states
    - count_region_av_products_installed
    - count_region_smart_screen
    - count_region_os_install_type_name
    - count_country_av_product_states
    - count_country_av_products_installed
    - count_country_smart_screen
    - count_country_os_install_type_name
    - count_city_av_product_states
    - count_city_av_products_installed
    - count_city_smart_screen
    - count_city_os_install_type_name
    - count_av_product_states_av_products_installed
    - count_av_product_states_smart_screen
    - count_av_product_states_os_install_type
    - count_av_products_installed_smart_screen
    - count_av_products_installed_os_install_type
    - count_smart_screen_os_install_type
    # - mul_system_volume_total_capacity_processor_core_count
    - div_system_volume_total_capacity_processor_core_count
    - mul_primary_disk_total_capacity_processor_core_count
    # - div_primary_disk_total_capacity_processor_core_count
    - mul_total_physical_ram_processor_core_count
    # - div_total_physical_ram_processor_core_count
    - mul_display_size_inches_processor_core_count
    # - div_display_size_inches_processor_core_count
    # - mul_display_resolution_horizontal_processor_core_count
    # - div_display_resolution_horizontal_processor_core_count
    # - mul_display_resolution_vertical_processor_core_count
    # - div_display_resolution_vertical_processor_core_count
    - div_system_volume_total_capacity_total_physical_ram
    - div_primary_disk_total_capacity_total_physical_ram
    - div_display_size_inches_total_physical_ram
    # - div_display_resolution_horizontal_total_physical_ram
    - div_display_resolution_vertical_total_physical_ram
    # - version_aggs_1
    - version_aggs_2
    - version_aggs_3
    # - version_aggs_4
    # - version_aggs_5
    - version_aggs_6
    - lda_engine_ver_av_products_installed_3
    - lda_app_ver_av_products_installed_3
    - lda_av_sig_ver_av_products_installed_3
    - lda_av_product_states_av_products_installed_3
    - lda_country_av_products_installed_3
    - lda_city_av_products_installed_3
    - lda_geo_name_av_products_installed_3
    # - lda_locale_english_name_av_products_installed_3
    - lda_os_build_lab_av_products_installed_3
    - lda_oem_model_av_products_installed_3
    - lda_processor_model_av_products_installed_3
    - lda_census_os_ver_av_products_installed_3
    - lda_firmware_ver_av_products_installed_3
    # - lda_region_av_products_installed_3
    - lda_engine_ver_smart_screen_3
    - lda_app_ver_smart_screen_3
    - lda_av_sig_ver_smart_screen_3
    - lda_av_product_states_smart_screen_3
    - lda_country_smart_screen_3
    - lda_city_smart_screen_3
    - lda_geo_name_smart_screen_3
    # - lda_locale_english_name_smart_screen_3
    - lda_os_build_lab_smart_screen_3
    - lda_oem_model_smart_screen_3
    - lda_processor_model_smart_screen_3
    - lda_census_os_ver_smart_screen_3
    - lda_firmware_ver_smart_screen_3
    # - lda_region_smart_screen_3
    - lda_engine_ver_activation_channel_3
    - lda_app_ver_activation_channel_3
    - lda_av_sig_ver_activation_channel_3
    - lda_av_product_states_activation_channel_3
    - lda_country_activation_channel_3
    - lda_city_activation_channel_3
    - lda_geo_name_activation_channel_3
    # - lda_locale_english_name_activation_channel_3
    - lda_os_build_lab_activation_channel_3
    - lda_oem_model_activation_channel_3
    - lda_processor_model_activation_channel_3
    - lda_census_os_ver_activation_channel_3
    - lda_firmware_ver_activation_channel_3
    # - lda_region_activation_channel_3
  count_encode:
    - engine_version
    - app_version
    - av_sig_version
    - organization_id
    - geo_name_id
    - locale_english_name_id
    - os_build_lab
    - os_build_lab_split_0
    - ie_ver_id
    - census_oem_name_id
    - census_os_version
    - census_os_build_number
    - census_os_build_revision
    - census_os_branch
    - census_os_install_type_name
    - census_processor_model_id
    - census_firmware_manufacturer_id
    - census_firmware_version_id
    # - hour_minute
    # - day_of_week
  category_encode:
    - av_product_states_id
    # - av_products_enabled
    # - os_suite
    - os_build_lab_split_1
    # - sku_edition
    - rtp_state_bitfield
    - smart_screen
    - census_mdc2_form_factor
    - census_chassis_type_name
    - census_power_platform_role_name
    - census_os_architecture
    - census_os_edition
    # - census_os_sku_name
    # - census_os_install_language_id
    - census_os_ui_locale_id
    - census_os_wu_auto_update_options_name
    - census_genuine_state_name
    - census_activation_channel
    # - census_processor_manufacturer_id
    # - census_primary_disk_type_name
    # - day
    # - hour
    # - minute
  rank_encode:
    - av_products_installed
    - census_total_physical_ram
    # - census_processor_core_count
    # - os_build_release_year_month
  target_encode:
    - country_id
    - city_id
    - wdft_region_id
    - census_oem_model_id

model:
  name: lightgbm
  model_params:
    boosting_type: gbdt
    objective: binary
    scale_pos_weight: 1.0
    learning_rate: 0.025
    num_leaves: 512
    max_depth: -1
    min_data_in_leaf: 100
    feature_fraction: 0.6
    bagging_fraction: 0.8
    bagging_freq: 1
    min_child_weight: 10.0
    min_split_gain: 0
    cat_l2: 15.0
    cat_smooth: 30.0
    lambda_l1: 1.0
    lambda_l2: 2.5
    monotone_constraints: null
    random_state: 8
    verbosity: -1
  train_params:
    num_boost_round: 10000
    verbose_eval: 100
    early_stopping_rounds: 200
    categorical_feature: auto

cv_strategy:
  method: StratifiedKFold
  n_splits: 5
  seed: 0

dataset:
  input_directory: 'data/input/'
  output_directory: 'data/output/'
  files:
    train: train.pkl
    target: target.pkl
    test: test.pkl
    sample_submit: sample_submission.csv

target: HasDetections

