---
use_cols:
  categorical:
    - RtpStateBitfield
    - AVProductStatesIdentifier
    - AVProductsInstalled
    - AVProductsEnabled
    - CountryIdentifier
    - CityIdentifier
    - OrganizationIdentifier
    - GeoNameIdentifier
    - LocaleEnglishNameIdentifier
    - SmartScreen
    - Census_MDC2FormFactor
    - Census_ChassisTypeName
    - Census_OSArchitecture
    - Census_OSEdition
    - Census_OSInstallTypeName
    - Census_OSUILocaleIdentifier
    - Census_OSWUAutoUpdateOptionsName
    - Census_GenuineStateName
    - Census_ActivationChannel
    - Census_ProcessorModelIdentifier
    - Census_ProcessorCoreCount
    - Census_ProcessorManufacturerIdentifier
    - Census_TotalPhysicalRAM
    - Census_OEMNameIdentifier
    - Census_OEMModelIdentifier
    - Census_InternalPrimaryDiagonalDisplaySizeInInches
    - Census_InternalPrimaryDisplayResolutionHorizontal
    - Census_InternalPrimaryDisplayResolutionVertical
    - Census_FirmwareManufacturerIdentifier
    - Wdft_IsGamer
    - Wdft_RegionIdentifier
  numerical:
    - Census_SystemVolumeTotalCapacity
    - Census_PrimaryDiskTotalCapacity 
  count:
    - EngineVersion
    - AppVersion
    - AvSigVersion
    - OsVer
    - OsBuildLab
    - IeVerIdentifier
    - Census_OSVersion
    - Census_OSBuildNumber
    - Census_OSBuildRevision
    - Census_OSBranch
    - Census_FirmwareVersionIdentifier
  pair_count:
    - col1: AVProductStatesIdentifier
      col2: AVProductsInstalled
    - col1: AVProductStatesIdentifier
      col2: Census_OSInstallTypeName
    - col1: AVProductStatesIdentifier
      col2: SmartScreen
    - col1: AVProductsInstalled
      col2: SmartScreen
    - col1: AVProductsInstalled
      col2: Census_OSInstallTypeName
    - col1: SmartScreen
      col2: Census_OSInstallTypeName
    - col1: CountryIdentifier
      col2: AVProductStatesIdentifier
    - col1: CountryIdentifier
      col2: AVProductsInstalled
    - col1: CountryIdentifier
      col2: SmartScreen
    - col1: CountryIdentifier
      col2: Census_OSInstallTypeName
    - col1: Wdft_RegionIdentifier
      col2: AVProductStatesIdentifier
    - col1: Wdft_RegionIdentifier
      col2: AVProductsInstalled
    - col1: Wdft_RegionIdentifier
      col2: SmartScreen
    - col1: Wdft_RegionIdentifier
      col2: Census_OSInstallTypeName

model:
  model_params:
    embed_dims:
      - column: RtpStateBitfield
        in: 8
        out: 4
      - column: AVProductStatesIdentifier
        in: 197
        out: 8
      - column: AVProductsInstalled
        in: 6
        out: 4
      - column: AVProductsEnabled
        in: 6
        out: 4
      - column: CountryIdentifier
        in: 185
        out: 8
      - column: CityIdentifier
        in: 1148
        out: 16
      - column: OrganizationIdentifier
        in: 21
        out: 8
      - column: GeoNameIdentifier
        in: 150
        out: 8
      - column: LocaleEnglishNameIdentifier
        in: 121
        out: 8
      - column: SmartScreen
        in: 9
        out: 4
      - column: Census_MDC2FormFactor
        in: 11
        out: 4
      - column: Census_ChassisTypeName
        in: 21
        out: 8
      - column: Census_OSArchitecture
        in: 3
        out: 2
      - column: Census_OSEdition
        in: 14
        out: 4
      - column: Census_OSInstallTypeName
        in: 9
        out: 4
      - column: Census_OSUILocaleIdentifier
        in: 43
        out: 8
      - column: Census_OSWUAutoUpdateOptionsName
        in: 6
        out: 4
      - column: Census_GenuineStateName
        in: 5
        out: 4
      - column: Census_ActivationChannel
        in: 6
        out: 4
      - column: Census_ProcessorModelIdentifier
        in: 721
        out: 16
      - column: Census_ProcessorCoreCount
        in: 13
        out: 4
      - column: Census_ProcessorManufacturerIdentifier
        in: 4
        out: 2
      - column: Census_TotalPhysicalRAM
        in: 24
        out: 8
      - column: Census_OEMNameIdentifier
        in: 151
        out: 8
      - column: Census_OEMModelIdentifier
        in: 1413
        out: 16
      - column: Census_InternalPrimaryDiagonalDisplaySizeInInches
        in: 159
        out: 8
      - column: Census_InternalPrimaryDisplayResolutionHorizontal
        in: 37
        out: 8
      - column: Census_InternalPrimaryDisplayResolutionVertical
        in: 32
        out: 8
      - column: Census_FirmwareManufacturerIdentifier
        in: 52
        out: 8
      - column: Wdft_IsGamer
        in: 3
        out: 2
      - column: Wdft_RegionIdentifier
        in: 16
        out: 4
  train_params:
    epochs: 1000 # early stop
    lr: 0.002
    batch_size: 2048
    seed: 12345

cv_strategy:
  method: StratifiedKFold
  n_splits: 5
  seed: 0

dataset:
  input_directory: 'data/input/'
  output_directory: 'data/output/'
  files:
    train: train.pkl
    target: target.pkl
    test: test.pkl
    sample_submit: sample_submission.csv

target: HasDetections

